version: '3.9'

services:
  database:
    image: docker.io/library/postgres:14.5-alpine3.16
    container_name: leetcode_database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
